kind: PersistentVolume
apiVersion: v1
metadata:
  name: lab10-pv-volume
  labels:
      type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/c/data" 
