apiVersion: batch/v1
kind: CronJob
metadata:
  name: sleepy-job
spec:
  jobTemplate:
    metadata:
      name: sleepy-job
    spec:
      template:
        spec:
          containers:
          - image: busybox
            name: sleepy-job
            command: ['sleep','300']
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/2 * * * *'
